/**
 * Provider registry. Each entry describes:
 *   - id / name / docs
 *   - keyPattern: regex that matches a raw key string (for auto-detect)
 *   - validate: how the Actions runner will validate the key
 *
 * Validation runs server-side in the user's GitHub Actions runner,
 * not in the browser. This registry is shared between the frontend
 * (for auto-detect) and scripts/validate.mjs (for actual HTTP calls).
 */

export type ValidationSpec = {
  method: "GET" | "POST";
  /** URL. `{key}` is substituted with the raw key (used for providers that accept the key in the query string, like Google). */
  url: string;
  /** Header name for the key, e.g. "Authorization". Omit for query-string auth. */
  authHeader?: string;
  /** How the key is embedded in the header value. `{key}` is substituted. Default: `Bearer {key}`. */
  authFormat?: string;
  /** Extra static headers. */
  headers?: Record<string, string>;
  /** POST body (JSON). */
  body?: unknown;
};

export type Provider = {
  id: string;
  name: string;
  docsUrl: string;
  /** Regex to detect keys of this provider. Anchored, case-sensitive unless noted. */
  keyPattern: RegExp;
  validate: ValidationSpec;
};

export const PROVIDERS: Provider[] = [
  {
    id: "openai",
    name: "OpenAI",
    docsUrl: "https://platform.openai.com/api-keys",
    keyPattern: /^sk-(?:proj-|svcacct-|admin-)?[A-Za-z0-9_-]{20,}$/,
    validate: { method: "GET", url: "https://api.openai.com/v1/models", authHeader: "Authorization" },
  },
  {
    id: "anthropic",
    name: "Anthropic",
    docsUrl: "https://console.anthropic.com/settings/keys",
    keyPattern: /^sk-ant-[A-Za-z0-9_-]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.anthropic.com/v1/models",
      authHeader: "x-api-key",
      authFormat: "{key}",
      headers: { "anthropic-version": "2023-06-01" },
    },
  },
  {
    id: "google",
    name: "Google Gemini",
    docsUrl: "https://aistudio.google.com/app/apikey",
    keyPattern: /^AIza[A-Za-z0-9_-]{35}$/,
    validate: { method: "GET", url: "https://generativelanguage.googleapis.com/v1beta/models?key={key}" },
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    docsUrl: "https://console.x.ai",
    keyPattern: /^xai-[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.x.ai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "groq",
    name: "Groq",
    docsUrl: "https://console.groq.com/keys",
    keyPattern: /^gsk_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.groq.com/openai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "mistral",
    name: "Mistral",
    docsUrl: "https://console.mistral.ai/api-keys/",
    keyPattern: /^[A-Za-z0-9]{32}$/,
    validate: { method: "GET", url: "https://api.mistral.ai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    docsUrl: "https://platform.deepseek.com/api_keys",
    keyPattern: /^sk-[a-f0-9]{32}$/,
    validate: { method: "GET", url: "https://api.deepseek.com/v1/models", authHeader: "Authorization" },
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    docsUrl: "https://openrouter.ai/keys",
    keyPattern: /^sk-or-v1-[a-f0-9]{64}$/,
    validate: { method: "GET", url: "https://openrouter.ai/api/v1/models", authHeader: "Authorization" },
  },
  {
    id: "perplexity",
    name: "Perplexity",
    docsUrl: "https://www.perplexity.ai/settings/api",
    keyPattern: /^pplx-[A-Za-z0-9]{40,}$/,
    validate: {
      method: "POST",
      url: "https://api.perplexity.ai/chat/completions",
      authHeader: "Authorization",
      body: { model: "sonar", messages: [{ role: "user", content: "hi" }], max_tokens: 1 },
    },
  },
  {
    id: "cohere",
    name: "Cohere",
    docsUrl: "https://dashboard.cohere.com/api-keys",
    keyPattern: /^[A-Za-z0-9]{40}$/,
    validate: { method: "GET", url: "https://api.cohere.com/v1/models", authHeader: "Authorization" },
  },
  {
    id: "together",
    name: "Together",
    docsUrl: "https://api.together.xyz/settings/api-keys",
    keyPattern: /^tgp_v1_[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://api.together.xyz/v1/models", authHeader: "Authorization" },
  },
  {
    id: "fireworks",
    name: "Fireworks",
    docsUrl: "https://fireworks.ai/account/api-keys",
    keyPattern: /^fw_[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.fireworks.ai/inference/v1/models", authHeader: "Authorization" },
  },
  {
    id: "cerebras",
    name: "Cerebras",
    docsUrl: "https://cloud.cerebras.ai/",
    keyPattern: /^csk-[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.cerebras.ai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "novita",
    name: "Novita",
    docsUrl: "https://novita.ai/settings/key-management",
    keyPattern: /^sk_[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://api.novita.ai/v3/openai/models", authHeader: "Authorization" },
  },
  {
    id: "anyscale",
    name: "Anyscale",
    docsUrl: "https://console.anyscale.com/",
    keyPattern: /^esecret_[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.endpoints.anyscale.com/v1/models", authHeader: "Authorization" },
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    docsUrl: "https://huggingface.co/settings/tokens",
    keyPattern: /^hf_[A-Za-z0-9]{30,}$/,
    validate: { method: "GET", url: "https://huggingface.co/api/whoami-v2", authHeader: "Authorization" },
  },
  {
    id: "replicate",
    name: "Replicate",
    docsUrl: "https://replicate.com/account/api-tokens",
    keyPattern: /^r8_[A-Za-z0-9]{35,}$/,
    validate: { method: "GET", url: "https://api.replicate.com/v1/account", authHeader: "Authorization", authFormat: "Token {key}" },
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    docsUrl: "https://elevenlabs.io/app/settings/api-keys",
    keyPattern: /^sk_[a-f0-9]{48}$/,
    validate: { method: "GET", url: "https://api.elevenlabs.io/v1/user", authHeader: "xi-api-key", authFormat: "{key}" },
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    docsUrl: "https://www.assemblyai.com/app/api-keys",
    keyPattern: /^[a-f0-9]{32}$/,
    validate: {
      method: "GET",
      url: "https://api.assemblyai.com/v2/transcript?limit=1",
      authHeader: "authorization",
      authFormat: "{key}",
    },
  },
  {
    id: "deepgram",
    name: "Deepgram",
    docsUrl: "https://console.deepgram.com/",
    keyPattern: /^[a-f0-9]{40}$/,
    validate: { method: "GET", url: "https://api.deepgram.com/v1/projects", authHeader: "Authorization", authFormat: "Token {key}" },
  },
  {
    id: "stability",
    name: "Stability AI",
    docsUrl: "https://platform.stability.ai/account/keys",
    keyPattern: /^sk-[A-Za-z0-9]{48,}$/,
    validate: { method: "GET", url: "https://api.stability.ai/v1/user/account", authHeader: "Authorization" },
  },
  {
    id: "runway",
    name: "Runway",
    docsUrl: "https://app.runwayml.com/settings/api",
    keyPattern: /^key_[A-Za-z0-9]{40,}$/,
    validate: {
      method: "GET",
      url: "https://api.dev.runwayml.com/v1/organization",
      authHeader: "Authorization",
      headers: { "X-Runway-Version": "2024-11-06" },
    },
  },
  {
    id: "luma",
    name: "Luma",
    docsUrl: "https://lumalabs.ai/dream-machine/api",
    keyPattern: /^luma-[A-Za-z0-9-]{36,}$/,
    validate: { method: "GET", url: "https://api.lumalabs.ai/dream-machine/v1/credits", authHeader: "Authorization" },
  },
  {
    id: "voyage",
    name: "Voyage AI",
    docsUrl: "https://dash.voyageai.com/",
    keyPattern: /^pa-[A-Za-z0-9_-]{40,}$/,
    validate: {
      method: "POST",
      url: "https://api.voyageai.com/v1/embeddings",
      authHeader: "Authorization",
      body: { input: ["ping"], model: "voyage-3-lite" },
    },
  },
  {
    id: "jina",
    name: "Jina AI",
    docsUrl: "https://jina.ai/",
    keyPattern: /^jina_[A-Za-z0-9]{50,}$/,
    validate: {
      method: "POST",
      url: "https://api.jina.ai/v1/embeddings",
      authHeader: "Authorization",
      body: { input: ["ping"], model: "jina-embeddings-v3" },
    },
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    docsUrl: "https://build.nvidia.com/",
    keyPattern: /^nvapi-[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://integrate.api.nvidia.com/v1/models", authHeader: "Authorization" },
  },
  {
    id: "github",
    name: "GitHub Models",
    docsUrl: "https://github.com/marketplace/models",
    keyPattern: /^(?:ghp_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{80,})$/,
    validate: { method: "GET", url: "https://models.github.ai/catalog/models", authHeader: "Authorization" },
  },
  {
    id: "hyperbolic",
    name: "Hyperbolic",
    docsUrl: "https://app.hyperbolic.xyz/settings",
    keyPattern: /^eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}$/,
    validate: { method: "GET", url: "https://api.hyperbolic.xyz/v1/models", authHeader: "Authorization" },
  },
  {
    id: "cartesia",
    name: "Cartesia",
    docsUrl: "https://play.cartesia.ai/keys",
    keyPattern: /^sk_car_[A-Za-z0-9_-]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.cartesia.ai/voices",
      authHeader: "X-API-Key",
      authFormat: "{key}",
      headers: { "Cartesia-Version": "2024-06-10" },
    },
  },
  {
    id: "sambanova",
    name: "SambaNova",
    docsUrl: "https://cloud.sambanova.ai/apis",
    keyPattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
    validate: { method: "GET", url: "https://api.sambanova.ai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    docsUrl: "https://studio.ai21.com/account/api-key",
    keyPattern: /^[A-Za-z0-9]{32,}$/,
    validate: {
      method: "POST",
      url: "https://api.ai21.com/studio/v1/chat/completions",
      authHeader: "Authorization",
      body: { model: "jamba-mini", messages: [{ role: "user", content: "hi" }], max_tokens: 1 },
    },
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    docsUrl: "https://app.leonardo.ai/api-access",
    keyPattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
    validate: { method: "GET", url: "https://cloud.leonardo.ai/api/rest/v1/me", authHeader: "Authorization" },
  },
  {
    id: "nomic",
    name: "Nomic Atlas",
    docsUrl: "https://atlas.nomic.ai/",
    keyPattern: /^nk-[A-Za-z0-9_-]{40,}$/,
    validate: {
      method: "POST",
      url: "https://api-atlas.nomic.ai/v1/embedding/text",
      authHeader: "Authorization",
      body: { model: "nomic-embed-text-v1.5", texts: ["ping"] },
    },
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    docsUrl: "https://www.firecrawl.dev/app/api-keys",
    keyPattern: /^fc-[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.firecrawl.dev/v1/team/credit-usage", authHeader: "Authorization" },
  },
  {
    id: "langsmith",
    name: "LangSmith",
    docsUrl: "https://smith.langchain.com/settings",
    keyPattern: /^lsv2_(?:pt|sk)_[a-f0-9]{32,}_[a-f0-9]{8,}$/,
    validate: {
      method: "GET",
      url: "https://api.smith.langchain.com/api/v1/workspaces",
      authHeader: "x-api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "twelvelabs",
    name: "Twelve Labs",
    docsUrl: "https://playground.twelvelabs.io/dashboard/api-key",
    keyPattern: /^tlk_[A-Za-z0-9]{30,}$/,
    validate: {
      method: "GET",
      url: "https://api.twelvelabs.io/v1.3/indexes?page_limit=1",
      authHeader: "x-api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "tavily",
    name: "Tavily",
    docsUrl: "https://app.tavily.com/home",
    keyPattern: /^tvly-[A-Za-z0-9-]{20,}$/,
    validate: {
      method: "POST",
      url: "https://api.tavily.com/search",
      authHeader: "Authorization",
      body: { query: "ping", max_results: 1 },
    },
  },
  {
    id: "exa",
    name: "Exa",
    docsUrl: "https://dashboard.exa.ai/api-keys",
    keyPattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
    validate: {
      method: "POST",
      url: "https://api.exa.ai/search",
      authHeader: "x-api-key",
      authFormat: "{key}",
      body: { query: "ping", numResults: 1 },
    },
  },
  {
    id: "pinecone",
    name: "Pinecone",
    docsUrl: "https://app.pinecone.io/",
    keyPattern: /^pcsk_[A-Za-z0-9_-]{40,}$/,
    validate: {
      method: "GET",
      url: "https://api.pinecone.io/indexes",
      authHeader: "Api-Key",
      authFormat: "{key}",
      headers: { "X-Pinecone-API-Version": "2024-07" },
    },
  },
  {
    id: "helicone",
    name: "Helicone",
    docsUrl: "https://us.helicone.ai/settings/api-keys",
    keyPattern: /^sk-helicone-[A-Za-z0-9-]{40,}$/,
    validate: { method: "GET", url: "https://api.helicone.ai/v1/user/query", authHeader: "Authorization" },
  },
  {
    id: "fal",
    name: "Fal.ai",
    docsUrl: "https://fal.ai/dashboard/keys",
    keyPattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[a-f0-9]{32,}$/,
    validate: {
      method: "GET",
      url: "https://rest.alpha.fal.ai/user",
      authHeader: "Authorization",
      authFormat: "Key {key}",
    },
  },
  {
    id: "segmind",
    name: "Segmind",
    docsUrl: "https://cloud.segmind.com/console/api-keys",
    keyPattern: /^SG_[A-Za-z0-9]{16,}$/,
    validate: {
      method: "GET",
      url: "https://api.segmind.com/v1/user",
      authHeader: "x-api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    docsUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    keyPattern: /^[a-f0-9]{32}\.[A-Za-z0-9]{16,}$/,
    validate: { method: "GET", url: "https://open.bigmodel.cn/api/paas/v4/models", authHeader: "Authorization" },
  },
  {
    id: "modal",
    name: "Modal",
    docsUrl: "https://modal.com/settings/tokens",
    keyPattern: /^ak-[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.modal.com/v1/apps", authHeader: "Authorization" },
  },
  {
    id: "runpod",
    name: "RunPod",
    docsUrl: "https://www.runpod.io/console/user/settings",
    keyPattern: /^rpa_[A-Z0-9]{40,}$/,
    validate: { method: "GET", url: "https://rest.runpod.io/v1/pods", authHeader: "Authorization" },
  },
  {
    id: "octoai",
    name: "Vercel v0",
    docsUrl: "https://v0.dev/chat/settings/keys",
    keyPattern: /^v1:[A-Za-z0-9]{20,}:[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.v0.dev/v1/user", authHeader: "Authorization" },
  },
  {
    id: "brave",
    name: "Brave Search",
    docsUrl: "https://api-dashboard.search.brave.com/",
    keyPattern: /^BSA[A-Za-z0-9_-]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.search.brave.com/res/v1/web/search?q=ping&count=1",
      authHeader: "X-Subscription-Token",
      authFormat: "{key}",
      headers: { Accept: "application/json" },
    },
  },
  {
    id: "apify",
    name: "Apify",
    docsUrl: "https://console.apify.com/settings/integrations",
    keyPattern: /^apify_api_[A-Za-z0-9]{30,}$/,
    validate: { method: "GET", url: "https://api.apify.com/v2/users/me", authHeader: "Authorization" },
  },
  {
    id: "browserbase",
    name: "Browserbase",
    docsUrl: "https://www.browserbase.com/settings",
    keyPattern: /^bb_(?:live|test)_[A-Za-z0-9_-]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.browserbase.com/v1/projects",
      authHeader: "X-BB-API-Key",
      authFormat: "{key}",
    },
  },
  {
    id: "portkey",
    name: "Portkey",
    docsUrl: "https://app.portkey.ai/api-keys",
    keyPattern: /^pk-[A-Za-z0-9]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.portkey.ai/v1/models",
      authHeader: "x-portkey-api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "langfuse",
    name: "Langfuse",
    docsUrl: "https://cloud.langfuse.com/",
    keyPattern: /^pk-lf-[0-9a-f-]{30,}$/,
    validate: {
      method: "GET",
      url: "https://cloud.langfuse.com/api/public/projects",
      authHeader: "Authorization",
      authFormat: "Basic {key}",
    },
  },
  {
    id: "resend",
    name: "Resend",
    docsUrl: "https://resend.com/api-keys",
    keyPattern: /^re_[A-Za-z0-9_]{20,}$/,
    validate: { method: "GET", url: "https://api.resend.com/api-keys", authHeader: "Authorization" },
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    docsUrl: "https://app.sendgrid.com/settings/api_keys",
    keyPattern: /^SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}$/,
    validate: { method: "GET", url: "https://api.sendgrid.com/v3/user/account", authHeader: "Authorization" },
  },
  {
    id: "notion",
    name: "Notion",
    docsUrl: "https://www.notion.so/my-integrations",
    keyPattern: /^(?:secret_|ntn_)[A-Za-z0-9]{43,}$/,
    validate: {
      method: "GET",
      url: "https://api.notion.com/v1/users",
      authHeader: "Authorization",
      headers: { "Notion-Version": "2022-06-28" },
    },
  },
  {
    id: "linear",
    name: "Linear",
    docsUrl: "https://linear.app/settings/api",
    keyPattern: /^lin_api_[A-Za-z0-9]{40,}$/,
    validate: {
      method: "POST",
      url: "https://api.linear.app/graphql",
      authHeader: "Authorization",
      authFormat: "{key}",
      body: { query: "{ viewer { id } }" },
    },
  },
  {
    id: "airtable",
    name: "Airtable",
    docsUrl: "https://airtable.com/create/tokens",
    keyPattern: /^pat[A-Za-z0-9]{14}\.[a-f0-9]{64}$/,
    validate: { method: "GET", url: "https://api.airtable.com/v0/meta/bases", authHeader: "Authorization" },
  },
  {
    id: "stripe",
    name: "Stripe",
    docsUrl: "https://dashboard.stripe.com/apikeys",
    keyPattern: /^(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.stripe.com/v1/customers?limit=1", authHeader: "Authorization" },
  },
  {
    id: "gitlab",
    name: "GitLab",
    docsUrl: "https://gitlab.com/-/user_settings/personal_access_tokens",
    keyPattern: /^glpat-[A-Za-z0-9_-]{20,}$/,
    validate: { method: "GET", url: "https://gitlab.com/api/v4/user", authHeader: "Authorization" },
  },
  {
    id: "hubspot",
    name: "HubSpot",
    docsUrl: "https://app.hubspot.com/settings/integrations/private-apps",
    keyPattern: /^pat-[a-z0-9]+-[a-f0-9-]{36}$/,
    validate: {
      method: "GET",
      url: "https://api.hubapi.com/crm/v3/objects/contacts?limit=1",
      authHeader: "Authorization",
    },
  },
  {
    id: "duffel",
    name: "Duffel",
    docsUrl: "https://app.duffel.com/access-tokens",
    keyPattern: /^duffel_(?:test|live)_[A-Za-z0-9_-]{30,}$/,
    validate: {
      method: "GET",
      url: "https://api.duffel.com/air/airports?limit=1",
      authHeader: "Authorization",
      headers: { "Duffel-Version": "v2", Accept: "application/json" },
    },
  },
  {
    id: "discord",
    name: "Discord Bot",
    docsUrl: "https://discord.com/developers/applications",
    keyPattern: /^[A-Za-z0-9]{24,28}\.[A-Za-z0-9_-]{6,7}\.[A-Za-z0-9_-]{27,}$/,
    validate: {
      method: "GET",
      url: "https://discord.com/api/v10/users/@me",
      authHeader: "Authorization",
      authFormat: "Bot {key}",
    },
  },
  {
    id: "neon",
    name: "Neon",
    docsUrl: "https://console.neon.tech/app/settings/api-keys",
    keyPattern: /^napi_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://console.neon.tech/api/v2/users/me", authHeader: "Authorization" },
  },
  {
    id: "netlify",
    name: "Netlify",
    docsUrl: "https://app.netlify.com/user/applications#personal-access-tokens",
    keyPattern: /^nfp_[A-Za-z0-9]{30,}$/,
    validate: { method: "GET", url: "https://api.netlify.com/api/v1/user", authHeader: "Authorization" },
  },
  {
    id: "render",
    name: "Render",
    docsUrl: "https://dashboard.render.com/u/settings#api-keys",
    keyPattern: /^rnd_[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.render.com/v1/services?limit=1", authHeader: "Authorization" },
  },
  {
    id: "sentry",
    name: "Sentry",
    docsUrl: "https://sentry.io/settings/account/api/auth-tokens/",
    keyPattern: /^sntrys_[A-Za-z0-9_]{40,}$/,
    validate: { method: "GET", url: "https://sentry.io/api/0/organizations/", authHeader: "Authorization" },
  },
  {
    id: "newrelic",
    name: "New Relic",
    docsUrl: "https://one.newrelic.com/admin-portal/api-keys/home",
    keyPattern: /^NRAK-[A-Z0-9]{27}$/,
    validate: {
      method: "GET",
      url: "https://api.newrelic.com/v2/applications.json",
      authHeader: "Api-Key",
      authFormat: "{key}",
    },
  },
  {
    id: "datastax",
    name: "DataStax Astra",
    docsUrl: "https://astra.datastax.com/",
    keyPattern: /^AstraCS:[A-Za-z0-9_+/=:-]{40,}$/,
    validate: { method: "GET", url: "https://api.astra.datastax.com/v2/databases", authHeader: "Authorization" },
  },
  {
    id: "deepl",
    name: "DeepL",
    docsUrl: "https://www.deepl.com/account/summary",
    keyPattern: /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}:fx$/,
    validate: {
      method: "GET",
      url: "https://api-free.deepl.com/v2/usage",
      authHeader: "Authorization",
      authFormat: "DeepL-Auth-Key {key}",
    },
  },
  {
    id: "posthog",
    name: "PostHog",
    docsUrl: "https://us.posthog.com/settings/user-api-keys",
    keyPattern: /^phx_[A-Za-z0-9_]{40,}$/,
    validate: { method: "GET", url: "https://us.posthog.com/api/users/@me/", authHeader: "Authorization" },
  },
  {
    id: "openpipe",
    name: "OpenPipe",
    docsUrl: "https://app.openpipe.ai/settings",
    keyPattern: /^opk_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://app.openpipe.ai/api/v1/models", authHeader: "Authorization" },
  },
  {
    id: "promptlayer",
    name: "PromptLayer",
    docsUrl: "https://promptlayer.com/settings/api-keys",
    keyPattern: /^pl_[A-Fa-f0-9]{32,}$/,
    validate: {
      method: "GET",
      url: "https://api.promptlayer.com/rest/get-all-prompt-templates?per_page=1",
      authHeader: "X-API-KEY",
      authFormat: "{key}",
    },
  },
  {
    id: "scrapingbee",
    name: "ScrapingBee",
    docsUrl: "https://app.scrapingbee.com/account/manage_api_key",
    keyPattern: /^[A-Z0-9]{80}$/,
    validate: { method: "GET", url: "https://app.scrapingbee.com/api/v1/usage?api_key={key}" },
  },
  {
    id: "mem0",
    name: "Mem0",
    docsUrl: "https://app.mem0.ai/dashboard/api-keys",
    keyPattern: /^m0-[A-Za-z0-9]{30,}$/,
    validate: {
      method: "GET",
      url: "https://api.mem0.ai/v1/entities/",
      authHeader: "Authorization",
      authFormat: "Token {key}",
    },
  },
  {
    id: "tinybird",
    name: "Tinybird",
    docsUrl: "https://ui.tinybird.co/tokens",
    keyPattern: /^p\.eyJ[A-Za-z0-9_.-]{50,}$/,
    validate: { method: "GET", url: "https://api.tinybird.co/v0/pipes", authHeader: "Authorization" },
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    docsUrl: "https://bitbucket.org/account/settings/app-passwords/",
    keyPattern: /^ATBB[A-Za-z0-9_-]{20,}$/,
    validate: { method: "GET", url: "https://api.bitbucket.org/2.0/user", authHeader: "Authorization" },
  },
  {
    id: "figma",
    name: "Figma",
    docsUrl: "https://www.figma.com/settings",
    keyPattern: /^figd_[A-Za-z0-9_-]{40,}$/,
    validate: {
      method: "GET",
      url: "https://api.figma.com/v1/me",
      authHeader: "X-Figma-Token",
      authFormat: "{key}",
    },
  },
  {
    id: "dropbox",
    name: "Dropbox",
    docsUrl: "https://www.dropbox.com/developers/apps",
    keyPattern: /^sl\.[A-Za-z0-9_-]{130,}$/,
    validate: {
      method: "POST",
      url: "https://api.dropboxapi.com/2/check/user",
      authHeader: "Authorization",
      body: { query: "ping" },
    },
  },
  {
    id: "asana",
    name: "Asana",
    docsUrl: "https://app.asana.com/0/my-apps",
    keyPattern: /^1\/[0-9]+:[a-f0-9]{32}$/,
    validate: { method: "GET", url: "https://app.asana.com/api/1.0/users/me", authHeader: "Authorization" },
  },
  {
    id: "clickup",
    name: "ClickUp",
    docsUrl: "https://app.clickup.com/settings/apps",
    keyPattern: /^pk_[0-9]+_[A-Z0-9]{30,}$/,
    validate: {
      method: "GET",
      url: "https://api.clickup.com/api/v2/user",
      authHeader: "Authorization",
      authFormat: "{key}",
    },
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    docsUrl: "https://www.klaviyo.com/account#api-keys-tab",
    keyPattern: /^pk_[a-f0-9]{50}$/,
    validate: {
      method: "GET",
      url: "https://a.klaviyo.com/api/accounts/",
      authHeader: "Authorization",
      authFormat: "Klaviyo-API-Key {key}",
      headers: { revision: "2024-10-15" },
    },
  },
  {
    id: "contentful",
    name: "Contentful",
    docsUrl: "https://app.contentful.com/account/profile/cma_tokens",
    keyPattern: /^CFPAT-[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://api.contentful.com/spaces", authHeader: "Authorization" },
  },
  {
    id: "circleci",
    name: "CircleCI",
    docsUrl: "https://app.circleci.com/settings/user/tokens",
    keyPattern: /^CCIPAT_[A-Za-z0-9_]{60,}$/,
    validate: {
      method: "GET",
      url: "https://circleci.com/api/v2/me",
      authHeader: "Circle-Token",
      authFormat: "{key}",
    },
  },
  {
    id: "dockerhub",
    name: "Docker Hub",
    docsUrl: "https://hub.docker.com/settings/personal-access-tokens",
    keyPattern: /^dckr_pat_[A-Za-z0-9_-]{20,}$/,
    validate: { method: "GET", url: "https://hub.docker.com/v2/user/", authHeader: "Authorization" },
  },
  {
    id: "npm",
    name: "npm",
    docsUrl: "https://www.npmjs.com/settings/~/tokens",
    keyPattern: /^npm_[A-Za-z0-9]{36}$/,
    validate: { method: "GET", url: "https://registry.npmjs.org/-/whoami", authHeader: "Authorization" },
  },
  {
    id: "buildkite",
    name: "Buildkite",
    docsUrl: "https://buildkite.com/user/api-access-tokens",
    keyPattern: /^bkua_[a-z0-9]{40}$/,
    validate: { method: "GET", url: "https://api.buildkite.com/v2/user", authHeader: "Authorization" },
  },
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    docsUrl: "https://app.launchdarkly.com/settings/authorization",
    keyPattern: /^api-[a-f0-9-]{36}$/,
    validate: {
      method: "GET",
      url: "https://app.launchdarkly.com/api/v2/caller-identity",
      authHeader: "Authorization",
      authFormat: "{key}",
    },
  },
  {
    id: "statsig",
    name: "Statsig",
    docsUrl: "https://console.statsig.com/api_keys",
    keyPattern: /^secret-[A-Za-z0-9]{40,}$/,
    validate: {
      method: "POST",
      url: "https://statsigapi.net/v1/check_gate",
      authHeader: "STATSIG-API-KEY",
      authFormat: "{key}",
      body: { user: { userID: "ping" }, gateName: "ping" },
    },
  },
  {
    id: "honeybadger",
    name: "Honeybadger",
    docsUrl: "https://app.honeybadger.io/users/edit",
    keyPattern: /^hbp_[A-Za-z0-9]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.honeybadger.io/v2/projects",
      authHeader: "Authorization",
      authFormat: "Token {key}",
    },
  },
  {
    id: "friendli",
    name: "Friendli",
    docsUrl: "https://suite.friendli.ai/user-settings/tokens",
    keyPattern: /^flp_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.friendli.ai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "typeform",
    name: "Typeform",
    docsUrl: "https://admin.typeform.com/account#/section/tokens",
    keyPattern: /^tfp_[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://api.typeform.com/me", authHeader: "Authorization" },
  },
  {
    id: "coingecko",
    name: "CoinGecko",
    docsUrl: "https://www.coingecko.com/en/developers/dashboard",
    keyPattern: /^CG-[A-Za-z0-9]{20,}$/,
    validate: {
      method: "GET",
      url: "https://api.coingecko.com/api/v3/ping",
      authHeader: "x-cg-demo-api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "abuseipdb",
    name: "AbuseIPDB",
    docsUrl: "https://www.abuseipdb.com/account/api",
    keyPattern: /^[a-f0-9]{80}$/,
    validate: {
      method: "GET",
      url: "https://api.abuseipdb.com/api/v2/check?ipAddress=1.1.1.1",
      authHeader: "Key",
      authFormat: "{key}",
      headers: { Accept: "application/json" },
    },
  },
  {
    id: "pexels",
    name: "Pexels",
    docsUrl: "https://www.pexels.com/api/",
    keyPattern: /^[A-Za-z0-9]{56}$/,
    validate: {
      method: "GET",
      url: "https://api.pexels.com/v1/curated?per_page=1",
      authHeader: "Authorization",
      authFormat: "{key}",
    },
  },
  {
    id: "pixabay",
    name: "Pixabay",
    docsUrl: "https://pixabay.com/api/docs/",
    keyPattern: /^[0-9]{8}-[a-f0-9]{25,}$/,
    validate: { method: "GET", url: "https://pixabay.com/api/?key={key}&per_page=3" },
  },
  {
    id: "glhf",
    name: "GLHF Chat",
    docsUrl: "https://glhf.chat/",
    keyPattern: /^glhf_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://glhf.chat/api/openai/v1/models", authHeader: "Authorization" },
  },
  {
    id: "wolframalpha",
    name: "Wolfram Alpha",
    docsUrl: "https://developer.wolframalpha.com/portal/myapps/",
    keyPattern: /^[A-Z0-9]{6}-[A-Z0-9]{10}$/,
    validate: {
      method: "GET",
      url: "https://api.wolframalpha.com/v2/query?input=1%2B1&output=JSON&appid={key}",
    },
  },
  {
    id: "ipinfo",
    name: "IPinfo",
    docsUrl: "https://ipinfo.io/account/token",
    keyPattern: /^[a-f0-9]{14}$/,
    validate: { method: "GET", url: "https://ipinfo.io/8.8.8.8/json?token={key}" },
  },
  {
    id: "currencyapi",
    name: "CurrencyAPI",
    docsUrl: "https://app.currencyapi.com/dashboard",
    keyPattern: /^cur_live_[A-Za-z0-9]{30,}$/,
    validate: { method: "GET", url: "https://api.currencyapi.com/v3/status?apikey={key}" },
  },
  {
    id: "scrapfly",
    name: "Scrapfly",
    docsUrl: "https://scrapfly.io/dashboard",
    keyPattern: /^scp-live-[a-f0-9]{32,}$/,
    validate: { method: "GET", url: "https://api.scrapfly.io/account?key={key}" },
  },
  {
    id: "supabase",
    name: "Supabase PAT",
    docsUrl: "https://supabase.com/dashboard/account/tokens",
    keyPattern: /^sbp_[a-f0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.supabase.com/v1/organizations", authHeader: "Authorization" },
  },
  {
    id: "baseten",
    name: "Baseten",
    docsUrl: "https://app.baseten.co/settings/account/api_keys",
    keyPattern: /^[A-Za-z0-9]{8}\.[A-Za-z0-9]{40,}$/,
    validate: {
      method: "GET",
      url: "https://app.baseten.co/api/v1/models",
      authHeader: "Authorization",
      authFormat: "Api-Key {key}",
    },
  },
  {
    id: "intercom",
    name: "Intercom",
    docsUrl: "https://app.intercom.com/a/apps/_/settings/developers",
    keyPattern: /^dG9r[A-Za-z0-9+/=]{60,}$/,
    validate: {
      method: "GET",
      url: "https://api.intercom.io/me",
      authHeader: "Authorization",
      headers: { "Intercom-Version": "2.11", Accept: "application/json" },
    },
  },
  {
    id: "calcom",
    name: "Cal.com",
    docsUrl: "https://app.cal.com/settings/developer/api-keys",
    keyPattern: /^cal_live_[a-f0-9]{32,}$/,
    validate: { method: "GET", url: "https://api.cal.com/v1/me?apiKey={key}" },
  },
  {
    id: "xata",
    name: "Xata",
    docsUrl: "https://app.xata.io/settings",
    keyPattern: /^xau_[A-Za-z0-9_-]{40,}$/,
    validate: { method: "GET", url: "https://api.xata.io/user", authHeader: "Authorization" },
  },
  {
    id: "triggerdev",
    name: "Trigger.dev",
    docsUrl: "https://cloud.trigger.dev/",
    keyPattern: /^tr_[a-z]+_[A-Za-z0-9]{20,}$/,
    validate: { method: "GET", url: "https://api.trigger.dev/api/v2/projects", authHeader: "Authorization" },
  },
  {
    id: "pushbullet",
    name: "Pushbullet",
    docsUrl: "https://www.pushbullet.com/#settings/account",
    keyPattern: /^o\.[A-Za-z0-9]{32,}$/,
    validate: {
      method: "GET",
      url: "https://api.pushbullet.com/v2/users/me",
      authHeader: "Access-Token",
      authFormat: "{key}",
    },
  },
  {
    id: "courier",
    name: "Courier",
    docsUrl: "https://app.courier.com/settings/api-keys",
    keyPattern: /^pk_(?:prod|test)_[A-Za-z0-9]{40,}$/,
    validate: { method: "GET", url: "https://api.courier.com/profiles", authHeader: "Authorization" },
  },
  {
    id: "mailersend",
    name: "MailerSend",
    docsUrl: "https://app.mailersend.com/domains",
    keyPattern: /^mlsn\.[a-f0-9]{60,}$/,
    validate: { method: "GET", url: "https://api.mailersend.com/v1/domains", authHeader: "Authorization" },
  },
  {
    id: "brevo",
    name: "Brevo",
    docsUrl: "https://app.brevo.com/settings/keys/api",
    keyPattern: /^xkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}$/,
    validate: {
      method: "GET",
      url: "https://api.brevo.com/v3/account",
      authHeader: "api-key",
      authFormat: "{key}",
    },
  },
  {
    id: "twitter",
    name: "Twitter / X",
    docsUrl: "https://developer.x.com/en/portal/dashboard",
    keyPattern: /^AAAAAAAAAAAAAAAAAAAAA[A-Za-z0-9%]{80,}$/,
    validate: { method: "GET", url: "https://api.twitter.com/2/users/me", authHeader: "Authorization" },
  },
  {
    id: "modrinth",
    name: "Modrinth",
    docsUrl: "https://modrinth.com/settings/pats",
    keyPattern: /^mrp_[A-Za-z0-9]{40,}$/,
    validate: {
      method: "GET",
      url: "https://api.modrinth.com/v3/user",
      authHeader: "Authorization",
      authFormat: "{key}",
    },
  },
  {
    id: "databricks",
    name: "Databricks",
    docsUrl: "https://docs.databricks.com/dev-tools/auth.html",
    keyPattern: /^dapi[a-f0-9]{32}(?:-\d)?$/,
    validate: {
      method: "GET",
      url: "https://community.cloud.databricks.com/api/2.0/clusters/list",
      authHeader: "Authorization",
    },
  },
  {
    id: "snyk",
    name: "Snyk",
    docsUrl: "https://app.snyk.io/account",
    keyPattern: /^snyk_[a-f0-9]{32,}$/,
    validate: {
      method: "GET",
      url: "https://api.snyk.io/rest/self?version=2024-10-15",
      authHeader: "Authorization",
      authFormat: "token {key}",
    },
  },
];

export const PROVIDER_BY_ID: Record<string, Provider> = Object.fromEntries(
  PROVIDERS.map((p) => [p.id, p]),
);
