// Server-side provider registry mirror. Kept in JS so scripts/validate.mjs
// can import it without a TS build step. Shape: id -> spec.
// spec: { m: "GET"|"POST", u: url, h?: header name, f?: header format ("{key}" placeholder), extra?: headers, body?: json }

export const PROVIDERS = {
  openai:      { m: "GET",  u: "https://api.openai.com/v1/models", h: "Authorization" },
  anthropic:   { m: "GET",  u: "https://api.anthropic.com/v1/models", h: "x-api-key", f: "{key}", extra: { "anthropic-version": "2023-06-01" } },
  google:      { m: "GET",  u: "https://generativelanguage.googleapis.com/v1beta/models?key={key}" },
  xai:         { m: "GET",  u: "https://api.x.ai/v1/models", h: "Authorization" },
  groq:        { m: "GET",  u: "https://api.groq.com/openai/v1/models", h: "Authorization" },
  mistral:     { m: "GET",  u: "https://api.mistral.ai/v1/models", h: "Authorization" },
  deepseek:    { m: "GET",  u: "https://api.deepseek.com/v1/models", h: "Authorization" },
  openrouter:  { m: "GET",  u: "https://openrouter.ai/api/v1/models", h: "Authorization" },
  perplexity:  { m: "POST", u: "https://api.perplexity.ai/chat/completions", h: "Authorization",
                 body: { model: "sonar", messages: [{ role: "user", content: "hi" }], max_tokens: 1 } },
  cohere:      { m: "GET",  u: "https://api.cohere.com/v1/models", h: "Authorization" },
  together:    { m: "GET",  u: "https://api.together.xyz/v1/models", h: "Authorization" },
  fireworks:   { m: "GET",  u: "https://api.fireworks.ai/inference/v1/models", h: "Authorization" },
  cerebras:    { m: "GET",  u: "https://api.cerebras.ai/v1/models", h: "Authorization" },
  novita:      { m: "GET",  u: "https://api.novita.ai/v3/openai/models", h: "Authorization" },
  anyscale:    { m: "GET",  u: "https://api.endpoints.anyscale.com/v1/models", h: "Authorization" },
  huggingface: { m: "GET",  u: "https://huggingface.co/api/whoami-v2", h: "Authorization" },
  replicate:   { m: "GET",  u: "https://api.replicate.com/v1/account", h: "Authorization", f: "Token {key}" },
  elevenlabs:  { m: "GET",  u: "https://api.elevenlabs.io/v1/user", h: "xi-api-key", f: "{key}" },
  assemblyai:  { m: "GET",  u: "https://api.assemblyai.com/v2/transcript?limit=1", h: "authorization", f: "{key}" },
  deepgram:    { m: "GET",  u: "https://api.deepgram.com/v1/projects", h: "Authorization", f: "Token {key}" },
  stability:   { m: "GET",  u: "https://api.stability.ai/v1/user/account", h: "Authorization" },
  runway:      { m: "GET",  u: "https://api.dev.runwayml.com/v1/organization", h: "Authorization", extra: { "X-Runway-Version": "2024-11-06" } },
  luma:        { m: "GET",  u: "https://api.lumalabs.ai/dream-machine/v1/credits", h: "Authorization" },
  voyage:      { m: "POST", u: "https://api.voyageai.com/v1/embeddings", h: "Authorization",
                 body: { input: ["ping"], model: "voyage-3-lite" } },
  jina:        { m: "POST", u: "https://api.jina.ai/v1/embeddings", h: "Authorization",
                 body: { input: ["ping"], model: "jina-embeddings-v3" } },
  nvidia:      { m: "GET",  u: "https://integrate.api.nvidia.com/v1/models", h: "Authorization" },
  github:      { m: "GET",  u: "https://models.github.ai/catalog/models", h: "Authorization" },
  hyperbolic:  { m: "GET",  u: "https://api.hyperbolic.xyz/v1/models", h: "Authorization" },
  cartesia:    { m: "GET",  u: "https://api.cartesia.ai/voices", h: "X-API-Key", f: "{key}", extra: { "Cartesia-Version": "2024-06-10" } },
  sambanova:   { m: "GET",  u: "https://api.sambanova.ai/v1/models", h: "Authorization" },
  ai21:        { m: "POST", u: "https://api.ai21.com/studio/v1/chat/completions", h: "Authorization",
                 body: { model: "jamba-mini", messages: [{ role: "user", content: "hi" }], max_tokens: 1 } },
  leonardo:    { m: "GET",  u: "https://cloud.leonardo.ai/api/rest/v1/me", h: "Authorization" },
  nomic:       { m: "POST", u: "https://api-atlas.nomic.ai/v1/embedding/text", h: "Authorization",
                 body: { model: "nomic-embed-text-v1.5", texts: ["ping"] } },
  firecrawl:   { m: "GET",  u: "https://api.firecrawl.dev/v1/team/credit-usage", h: "Authorization" },
  langsmith:   { m: "GET",  u: "https://api.smith.langchain.com/api/v1/workspaces", h: "x-api-key", f: "{key}" },
  twelvelabs:  { m: "GET",  u: "https://api.twelvelabs.io/v1.3/indexes?page_limit=1", h: "x-api-key", f: "{key}" },
  tavily:      { m: "POST", u: "https://api.tavily.com/search", h: "Authorization",
                 body: { query: "ping", max_results: 1 } },
  exa:         { m: "POST", u: "https://api.exa.ai/search", h: "x-api-key", f: "{key}",
                 body: { query: "ping", numResults: 1 } },
  pinecone:    { m: "GET",  u: "https://api.pinecone.io/indexes", h: "Api-Key", f: "{key}", extra: { "X-Pinecone-API-Version": "2024-07" } },
  helicone:    { m: "GET",  u: "https://api.helicone.ai/v1/user/query", h: "Authorization" },
  fal:         { m: "GET",  u: "https://rest.alpha.fal.ai/user", h: "Authorization", f: "Key {key}" },
  segmind:     { m: "GET",  u: "https://api.segmind.com/v1/user", h: "x-api-key", f: "{key}" },
  zhipu:       { m: "GET",  u: "https://open.bigmodel.cn/api/paas/v4/models", h: "Authorization" },
  modal:       { m: "GET",  u: "https://api.modal.com/v1/apps", h: "Authorization" },
  runpod:      { m: "GET",  u: "https://rest.runpod.io/v1/pods", h: "Authorization" },
  octoai:      { m: "GET",  u: "https://api.v0.dev/v1/user", h: "Authorization" },
  brave:       { m: "GET",  u: "https://api.search.brave.com/res/v1/web/search?q=ping&count=1", h: "X-Subscription-Token", f: "{key}", extra: { Accept: "application/json" } },
  apify:       { m: "GET",  u: "https://api.apify.com/v2/users/me", h: "Authorization" },
  browserbase: { m: "GET",  u: "https://api.browserbase.com/v1/projects", h: "X-BB-API-Key", f: "{key}" },
  portkey:     { m: "GET",  u: "https://api.portkey.ai/v1/models", h: "x-portkey-api-key", f: "{key}" },
  langfuse:    { m: "GET",  u: "https://cloud.langfuse.com/api/public/projects", h: "Authorization", f: "Basic {key}" },
  resend:      { m: "GET",  u: "https://api.resend.com/api-keys", h: "Authorization" },
  sendgrid:    { m: "GET",  u: "https://api.sendgrid.com/v3/user/account", h: "Authorization" },
  notion:      { m: "GET",  u: "https://api.notion.com/v1/users", h: "Authorization", extra: { "Notion-Version": "2022-06-28" } },
  linear:      { m: "POST", u: "https://api.linear.app/graphql", h: "Authorization", f: "{key}",
                 body: { query: "{ viewer { id } }" } },
  airtable:    { m: "GET",  u: "https://api.airtable.com/v0/meta/bases", h: "Authorization" },
  stripe:      { m: "GET",  u: "https://api.stripe.com/v1/customers?limit=1", h: "Authorization" },
  gitlab:      { m: "GET",  u: "https://gitlab.com/api/v4/user", h: "Authorization" },
  hubspot:     { m: "GET",  u: "https://api.hubapi.com/crm/v3/objects/contacts?limit=1", h: "Authorization" },
  duffel:      { m: "GET",  u: "https://api.duffel.com/air/airports?limit=1", h: "Authorization", extra: { "Duffel-Version": "v2", Accept: "application/json" } },
  discord:     { m: "GET",  u: "https://discord.com/api/v10/users/@me", h: "Authorization", f: "Bot {key}" },
  neon:        { m: "GET",  u: "https://console.neon.tech/api/v2/users/me", h: "Authorization" },
  netlify:     { m: "GET",  u: "https://api.netlify.com/api/v1/user", h: "Authorization" },
  render:      { m: "GET",  u: "https://api.render.com/v1/services?limit=1", h: "Authorization" },
  sentry:      { m: "GET",  u: "https://sentry.io/api/0/organizations/", h: "Authorization" },
  newrelic:    { m: "GET",  u: "https://api.newrelic.com/v2/applications.json", h: "Api-Key", f: "{key}" },
  datastax:    { m: "GET",  u: "https://api.astra.datastax.com/v2/databases", h: "Authorization" },
  deepl:       { m: "GET",  u: "https://api-free.deepl.com/v2/usage", h: "Authorization", f: "DeepL-Auth-Key {key}" },
  posthog:     { m: "GET",  u: "https://us.posthog.com/api/users/@me/", h: "Authorization" },
  openpipe:    { m: "GET",  u: "https://app.openpipe.ai/api/v1/models", h: "Authorization" },
  promptlayer: { m: "GET",  u: "https://api.promptlayer.com/rest/get-all-prompt-templates?per_page=1", h: "X-API-KEY", f: "{key}" },
  scrapingbee: { m: "GET",  u: "https://app.scrapingbee.com/api/v1/usage?api_key={key}" },
  mem0:        { m: "GET",  u: "https://api.mem0.ai/v1/entities/", h: "Authorization", f: "Token {key}" },
  tinybird:    { m: "GET",  u: "https://api.tinybird.co/v0/pipes", h: "Authorization" },
  bitbucket:   { m: "GET",  u: "https://api.bitbucket.org/2.0/user", h: "Authorization" },
  figma:       { m: "GET",  u: "https://api.figma.com/v1/me", h: "X-Figma-Token", f: "{key}" },
  dropbox:     { m: "POST", u: "https://api.dropboxapi.com/2/check/user", h: "Authorization",
                 body: { query: "ping" } },
  asana:       { m: "GET",  u: "https://app.asana.com/api/1.0/users/me", h: "Authorization" },
  clickup:     { m: "GET",  u: "https://api.clickup.com/api/v2/user", h: "Authorization", f: "{key}" },
  klaviyo:     { m: "GET",  u: "https://a.klaviyo.com/api/accounts/", h: "Authorization", f: "Klaviyo-API-Key {key}", extra: { revision: "2024-10-15" } },
  contentful:  { m: "GET",  u: "https://api.contentful.com/spaces", h: "Authorization" },
  circleci:    { m: "GET",  u: "https://circleci.com/api/v2/me", h: "Circle-Token", f: "{key}" },
  dockerhub:   { m: "GET",  u: "https://hub.docker.com/v2/user/", h: "Authorization" },
  npm:         { m: "GET",  u: "https://registry.npmjs.org/-/whoami", h: "Authorization" },
  buildkite:   { m: "GET",  u: "https://api.buildkite.com/v2/user", h: "Authorization" },
  launchdarkly:{ m: "GET",  u: "https://app.launchdarkly.com/api/v2/caller-identity", h: "Authorization", f: "{key}" },
  statsig:     { m: "POST", u: "https://statsigapi.net/v1/check_gate", h: "STATSIG-API-KEY", f: "{key}",
                 body: { user: { userID: "ping" }, gateName: "ping" } },
  honeybadger: { m: "GET",  u: "https://api.honeybadger.io/v2/projects", h: "Authorization", f: "Token {key}" },
  friendli:    { m: "GET",  u: "https://api.friendli.ai/v1/models", h: "Authorization" },
  typeform:    { m: "GET",  u: "https://api.typeform.com/me", h: "Authorization" },
  coingecko:   { m: "GET",  u: "https://api.coingecko.com/api/v3/ping", h: "x-cg-demo-api-key", f: "{key}" },
  abuseipdb:   { m: "GET",  u: "https://api.abuseipdb.com/api/v2/check?ipAddress=1.1.1.1", h: "Key", f: "{key}", extra: { Accept: "application/json" } },
  pexels:      { m: "GET",  u: "https://api.pexels.com/v1/curated?per_page=1", h: "Authorization", f: "{key}" },
  pixabay:     { m: "GET",  u: "https://pixabay.com/api/?key={key}&per_page=3" },
  glhf:        { m: "GET",  u: "https://glhf.chat/api/openai/v1/models", h: "Authorization" },
  wolframalpha:{ m: "GET",  u: "https://api.wolframalpha.com/v2/query?input=1%2B1&output=JSON&appid={key}" },
  ipinfo:      { m: "GET",  u: "https://ipinfo.io/8.8.8.8/json?token={key}" },
  currencyapi: { m: "GET",  u: "https://api.currencyapi.com/v3/status?apikey={key}" },
  scrapfly:    { m: "GET",  u: "https://api.scrapfly.io/account?key={key}" },
  supabase:    { m: "GET",  u: "https://api.supabase.com/v1/organizations", h: "Authorization" },
  baseten:     { m: "GET",  u: "https://app.baseten.co/api/v1/models", h: "Authorization", f: "Api-Key {key}" },
  intercom:    { m: "GET",  u: "https://api.intercom.io/me", h: "Authorization", extra: { "Intercom-Version": "2.11", Accept: "application/json" } },
  calcom:      { m: "GET",  u: "https://api.cal.com/v1/me?apiKey={key}" },
  xata:        { m: "GET",  u: "https://api.xata.io/user", h: "Authorization" },
  triggerdev:  { m: "GET",  u: "https://api.trigger.dev/api/v2/projects", h: "Authorization" },
  pushbullet:  { m: "GET",  u: "https://api.pushbullet.com/v2/users/me", h: "Access-Token", f: "{key}" },
  courier:     { m: "GET",  u: "https://api.courier.com/profiles", h: "Authorization" },
  mailersend:  { m: "GET",  u: "https://api.mailersend.com/v1/domains", h: "Authorization" },
  brevo:       { m: "GET",  u: "https://api.brevo.com/v3/account", h: "api-key", f: "{key}" },
  twitter:     { m: "GET",  u: "https://api.twitter.com/2/users/me", h: "Authorization" },
  modrinth:    { m: "GET",  u: "https://api.modrinth.com/v3/user", h: "Authorization", f: "{key}" },
  databricks:  { m: "GET",  u: "https://community.cloud.databricks.com/api/2.0/clusters/list", h: "Authorization" },
  snyk:        { m: "GET",  u: "https://api.snyk.io/rest/self?version=2024-10-15", h: "Authorization", f: "token {key}" },
};
